# Generated by Django 4.2.6 on 2023-10-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_favorite_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="recipetag",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="shoppingcart",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_user_recipe_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipetag",
            constraint=models.UniqueConstraint(
                fields=("recipe", "tag"), name="unique_recipe_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_user_recipe_cart"
            ),
        ),
    ]
