# Generated by Django 4.2.6 on 2023-10-18 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_alter_subscription_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscription",
            new_name="Subscriber",
        ),
        migrations.AlterModelTable(
            name="subscriber",
            table=None,
        ),
    ]
